apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: argo-cd
  namespace: kube-system
spec:
  repo: https://argoproj.github.io/argo-helm
  chart: argo-cd
  targetNamespace: argocd
  version: 7.8.2
  createNamespace: true
  valuesContent: |-
    configs:
      params:
        server.insecure: true
