- name: Setup K3s Single Node Cluster
  hosts: k3s_nodes
  become: true
  gather_facts: false

  tasks:
    - name: Update machine
      package:
        name: '*'
        state: latest

    - name: Ensure required directories exist
      file:
        path: /etc/rancher/k3s
        state: directory
        mode: '0755'

    - name: Apply K3s configuration template
      template:
        src: ../templates/config.yaml.j2
        dest: /etc/rancher/k3s/config.yaml
        mode: '0644'

    - name: Install K3s
      shell: curl -sfL https://get.k3s.io | sh -
