version: '3'

tasks:

  build:
    description: "Build the K3s First Server Node"
    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_create.yaml -e "@vars/k3s-server-node-config.yaml"

  clean:
    description: "Clean the K3s First Server Node"

    cmds:
      - ansible-playbook -i inventory.ini playbooks/k3s_destroy.yaml -e "@vars/k3s-server-node-config.yaml"