apiVersion: v1
kind: Namespace
metadata:
  name: kubevirt-hyperconverged

---
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  annotations:
    deployOVS: 'false'
  name: kubevirt-hyperconverged
  namespace: kubevirt-hyperconverged
spec: {}