apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-tektoncd-operator
  namespace: operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  channel: alpha
  name: tektoncd-operator
  source: operatorhubio-catalog
  sourceNamespace: olm